### ISSUE TITLE
"data-theme=dark" only for inputs as intended

### ISSUE THREAD

**Issue by ghost** [pelinoleg/Custom-Css-Forms#1]
First I would like to thank you for this beautiful CSS; Really eye pleasing.

My question is: Can I only apply style 'as intended on input elements' and not background or anything other than that (links ...)

I was integrating CCF with Chota.css library which is my root style, Chota already has dark mode for `document.body.dark` while CCF works with `document.html.data-theme=dark`, in this case, they can coexist nicely but if only CCF only acts on inputs and not anything else like background color.

**Comment by pelinoleg** [comment]
Thank you :)

I changed a little the behavior of the styles. Now demo styles are not applied by default.

But also now, in order to apply styles to forms, you need to put the class `.custom-form`

for example:
`<input type = "text" class = "custom-form" />`

**Comment by ghost** [comment]
This is just great really ! Thanks a lot, 
I think this resolves the issue, I'm closing it before testing.
