### ISSUE TITLE
Incorrect show html for File Upload/Color Picker

### ISSUE THREAD

**Issue by HamptonNorth** [pelinoleg/Custom-Css-Forms#2]
![image](https://github.com/pelinoleg/CSSformalize/assets/1650551/0ea05f9d-288d-40c6-bc4e-cd217126045c)

Should be something like:
```html
<input class="cform cform-custom-file" type="file">
<input type="color" class="cform cform-custom-picker">
```
I think! Thanks for you work on this.

**Comment by pelinoleg** [comment]
Yes, you're right! 
Thank you, I'll definitely fix it.

**Comment by HamptonNorth** [comment]
Impressive turnaround
